const __ = undefined;
const _ = {
    unchecked: 'crop_square',
    checked: 'checked',
    checks: 'done_all',
    unchecks: 'filter_none',
    refresh: 'refresh',
    link: 'link',
    delete: 'delete',
    save: 'save',
    upload: 'cloud_upload',
    expand: 'keyboard_arrow_down',
    collapse: 'keyboard_arrow_up',
    down: 'keyboard_arrow_down',
    up: 'keyboard_arrow_up',
    left: 'keyboard_arrow_left',
    right: 'keyboard_arrow_right',
    clear: 'clear',
    folder: 'folder',
    file: 'description',
    video: 'ondemand_video',
    subtitles: 'subtitles',
    music: 'music_note',
    close: 'close',
    ok: 'done',
    add: 'add',
    remove: 'remove',
    search: 'search',
    none: 'none',
    unset: 'unset',
    clear_inputs: 'backspace',
    clear_fields: 'clear_all',
    timeout: 10,
    monitored: 'visibility',
    unmonitored: 'visibility_off',
    expando: "unfold_more",
    download: 'get_app',
    scroll_top: 'vertical_align_top',
    select: 'add_circle_outline',
    deselect: 'remove_circle_outline',
    play: 'play_arrow',
    resize: 'vertical_align_center',
    book: 'menu_book',
    clearNotifications: 'clear_all',
    edit: 'edit',
    copy: 'link'

};
Object.freeze(_)