POST {{uri}}
Content-Type: application/json

{"jsonrpc": "2.0", "method": "Player.GetActivePlayers", "id": 1}

### { "id": 1, "jsonrpc": "2.0", "result": [{"playerid": 1, "playertype": "internal", "type": "video"}]}
POST {{uri}}
Content-Type: application/json

{"jsonrpc": "2.0", "method": "Player.GetItem", "params": { "properties": ["file"], "playerid": 1 }, "id": "VideoGetItem"}

### {"id": "VideoGetItem", "jsonrpc": "2.0", "result": {"item": {
#      "file": "smb://192.168.0.5/z/_cat_video/Paul_Dinning/20160919-Sounds and Videos for Dogs 🐶 Beautiful Woodland Birds [-ppwDqttDTo].conv.mkv",
#      "label": "20160919-Sounds and Videos for Dogs 🐶 Beautiful Woodland Birds [-ppwDqttDTo].conv.mkv",
#      "type": "unknown"}}}

POST {{uri}}
Content-Type: application/json

{"jsonrpc": "2.0", "method": "Player.PlayPause", "params": { "playerid": 1 }, "id": 1}
####

POST {{uri}}
Content-Type: application/json

{"jsonrpc":"2.0","method":"Player.Seek","params": {"playerid": 1, "value": {"seconds":940}}}

###{"jsonrpc": "2.0", "method": "Input.ExecuteAction", "params": { "action": "playpause" }, "id": 1}

###
GET {{uri}}?request={"jsonrpc":"2.0","method":"Player.GetPropertes","params":{"data":{"player":{"playerid":1}}}}
Content-Type: application/json

{"jsonrpc":"2.0","method":"Player.OnPropertyChanged","params":{"data":{"player":{"playerid":1}}}}


###

POST {{uri}}
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "Player.GetProperties",
  "id": 1,
  "params": {
    "playerid": 1,
    "properties": [
      "position", "percentage", "time", "totaltime"
    ]
  }
}